"""Digest Builder Module.

Builds the weekly digest in both HTML and plain-text form:

* **Top 20** most relevant articles: full metadata + abstract + summary +
  relevance explanation.
* **Remaining** relevant articles: title + authors + journal only.
"""
from __future__ import annotations

import html
from dataclasses import dataclass
from datetime import date
from typing import Optional

from .harvest import Article

TOP_N = 20


@dataclass
class Digest:
    subject: str
    html: str
    text: str
    total: int
    top_count: int


def _authors_str(article: Article) -> str:
    if not article.authors:
        return "Unknown authors"
    if len(article.authors) > 6:
        return ", ".join(article.authors[:6]) + " et al."
    return ", ".join(article.authors)


def _esc(text: Optional[str]) -> str:
    return html.escape(text or "")


# --------------------------------------------------------------------------- #
# HTML
# --------------------------------------------------------------------------- #
def _html_top_article(i: int, a: Article) -> str:
    link = f'<a href="{_esc(a.url)}">{_esc(a.title)}</a>' if a.url else _esc(a.title)
    doi = f'<div class="doi">DOI: {_esc(a.doi)}</div>' if a.doi else ""
    summary = f'<p><strong>Summary:</strong> {_esc(a.summary)}</p>' if a.summary else ""
    explanation = (f'<p class="why"><strong>Why relevant:</strong> '
                   f'{_esc(a.relevance_explanation)}</p>' if a.relevance_explanation else "")
    return f"""
    <div class="article">
      <h3>{i}. {link}</h3>
      <div class="meta">{_esc(_authors_str(a))} &middot; <em>{_esc(a.journal)}</em>
        &middot; {_esc(a.publication_date or "")} &middot;
        <span class="score">Score {a.final_score:.0f}/100</span></div>
      {doi}
      <p class="abstract">{_esc(a.abstract)}</p>
      {summary}
      {explanation}
    </div>"""


def _html_rest_row(a: Article) -> str:
    title = f'<a href="{_esc(a.url)}">{_esc(a.title)}</a>' if a.url else _esc(a.title)
    return (f"<li>{title} — {_esc(_authors_str(a))} "
            f"<em>({_esc(a.journal)})</em></li>")


def build_html(top: list[Article], rest: list[Article], week_of: date) -> str:
    top_html = "\n".join(_html_top_article(i + 1, a) for i, a in enumerate(top))
    rest_html = "\n".join(_html_rest_row(a) for a in rest)
    rest_section = (
        f'<h2>Other relevant articles ({len(rest)})</h2><ul class="rest">{rest_html}</ul>'
        if rest else ""
    )
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
          color:#1a1a1a; line-height:1.5; max-width:760px; margin:0 auto; padding:16px; }}
  h1 {{ font-size:22px; }} h2 {{ font-size:18px; margin-top:28px; border-bottom:2px solid #eee; padding-bottom:4px; }}
  h3 {{ font-size:16px; margin-bottom:2px; }}
  .meta {{ color:#555; font-size:13px; margin-bottom:6px; }}
  .doi {{ color:#888; font-size:12px; }}
  .score {{ color:#0a7d33; font-weight:600; }}
  .abstract {{ font-size:14px; }} .why {{ color:#444; font-size:14px; }}
  .article {{ margin-bottom:22px; }}
  ul.rest li {{ margin-bottom:6px; font-size:14px; }}
  .footer {{ color:#999; font-size:12px; margin-top:30px; border-top:1px solid #eee; padding-top:8px; }}
</style></head><body>
  <h1>Weekly Journal Digest — week of {week_of.isoformat()}</h1>
  <p>Top {len(top)} most relevant new articles this week.</p>
  {top_html}
  {rest_section}
  <div class="footer">Generated by Weekly Journal Digest System.</div>
</body></html>"""


# --------------------------------------------------------------------------- #
# Plain text
# --------------------------------------------------------------------------- #
def _text_top_article(i: int, a: Article) -> str:
    lines = [
        f"{i}. {a.title}",
        f"   {_authors_str(a)} | {a.journal} | {a.publication_date or ''} | Score {a.final_score:.0f}/100",
    ]
    if a.doi:
        lines.append(f"   DOI: {a.doi}")
    if a.url:
        lines.append(f"   URL: {a.url}")
    lines.append(f"   Abstract: {a.abstract}")
    if a.summary:
        lines.append(f"   Summary: {a.summary}")
    if a.relevance_explanation:
        lines.append(f"   Why relevant: {a.relevance_explanation}")
    return "\n".join(lines)


def build_text(top: list[Article], rest: list[Article], week_of: date) -> str:
    out = [f"WEEKLY JOURNAL DIGEST — week of {week_of.isoformat()}",
           f"Top {len(top)} most relevant new articles.", ""]
    out += [_text_top_article(i + 1, a) + "\n" for i, a in enumerate(top)]
    if rest:
        out.append(f"OTHER RELEVANT ARTICLES ({len(rest)})")
        out += [f"- {a.title} — {_authors_str(a)} ({a.journal})" for a in rest]
    out.append("\n-- Generated by Weekly Journal Digest System.")
    return "\n".join(out)


def build_digest(articles: list[Article], week_of: Optional[date] = None,
                 top_n: int = TOP_N) -> Digest:
    """Assemble the digest from already-scored, threshold-filtered articles."""
    week_of = week_of or date.today()
    top = articles[:top_n]
    rest = articles[top_n:]
    subject = f"Weekly Journal Digest — {len(articles)} new articles (week of {week_of.isoformat()})"
    return Digest(
        subject=subject,
        html=build_html(top, rest, week_of),
        text=build_text(top, rest, week_of),
        total=len(articles),
        top_count=len(top),
    )


def build_heartbeat(week_of: Optional[date] = None) -> Digest:
    """A short 'system ran successfully, no new articles' message."""
    week_of = week_of or date.today()
    subject = f"Weekly Journal Digest — no new articles (week of {week_of.isoformat()})"
    text = (f"The Weekly Journal Digest ran successfully on {week_of.isoformat()} "
            f"but found no new relevant articles this week.")
    html_body = f"<html><body><p>{text}</p></body></html>"
    return Digest(subject=subject, html=html_body, text=text, total=0, top_count=0)
